### Регистрация

POST {{server}}/api/user/register
Content-Type: application/json

{
  "name": "some user name",
  "email": "{{email}}",
  "password": "{{password}}",
  "device": "other",
  "device_id": "{{uuid}}"
}

### Авторизация

POST {{server}}/api/user/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "device": "other",
  "device_id": "{{uuid}}"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Авторизация неудачная

POST {{server}}/api/user/login
Content-Type: application/json

{
  "email": "asdasfda@asdasd.asd",
  "password": "{{password}}",
  "device": "other",
  "device_id": "{{uuid}}"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Профиль

GET {{server}}/api/user/profile
accept: application/json
Authorization: Bearer {{auth_token}}
