### Регистрация

POST {{server}}/api/user/register
Content-Type: application/json

{
  "name": "some user name",
  "email": "{{email}}",
  "password": "{{password}}",
  "device": "other",
  "device_id": "{{uuid}}"
}

### Авторизация

POST {{server}}/api/user/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "device": "other",
  "device_id": "{{uuid}}"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Авторизация неудачная

POST {{server}}/api/user/login
Content-Type: application/json

{
  "email": "asdasfda@asdasd.asd",
  "password": "{{password}}",
  "device": "other",
  "device_id": "{{uuid}}"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Профиль

GET {{server}}/api/user/profile
accept: application/json
Authorization: Bearer {{auth_token}}

### проверить auth token

GET {{server}}/api/auth/check
accept: application/json
Authorization: Bearer {{auth_token}}

### Получить refresh token

GET {{server}}/api/auth/refresh-token
accept: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.global.set("refresh_token", response.body.token);
%}

### обновить auth token

GET {{server}}/api/auth/refresh
accept: application/json
Authorization: Bearer {{refresh_token}}

> {%
    client.global.set("auth_token", response.body.token);
%}

### проверить refresh token

GET {{server}}/api/auth/check
accept: application/json
Authorization: Bearer {{refresh_token}}


### logout

GET {{server}}/api/auth/logout
accept: application/json
Authorization: Bearer {{auth_token}}
