ktor:
  application:
    modules:
      - ru.xsrv.todo.ApplicationKt.module
  deployment:
    port: 8080
    watch:  # development
      - classes
      - resources
  development: true
  behind-proxy: false

db: # база данных, in-memory не работает с текущими настройками движка ktor, можно найти в db пакете Main.kt и поиграть с in-memory для тестов
  #url: "jdbc:sqlite:file:test?mode=memory&cache=shared"
  url: "jdbc:sqlite:./data/data.db"
  #url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
  user: "root"
  driver: "org.sqlite.JDBC"
  #driver: "org.h2.Driver"
  password: ""

jwt:  # JWT для /api
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor todo app"
  secret: "shared_jwt_secret_change_after_deploy!!"
#  ttl: 60 # минута
  ttl: 86400 # сутки
  refresh-ttl: 2592000 # 30 дней

auth:
  basic-admin-auth: # доступ к /admin панели
    user: admin
    password: admin
  basic-doc-auth: # доступ к /openapi панели
    user: doc
    password: doc

